name: Build Softfloat MIPS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Build MIPSLE Softfloat Binaries
        run: |
          ROOT_DIR=$(pwd)
          mkdir -p "$ROOT_DIR/build"
          
          # Заходим в директорию headless, где лежит go.mod
          cd "$ROOT_DIR/headless"
          
          # Собираем все утилиты из headless/cmd/
          for cmd in cmd/*; do
            if [ -d "$cmd" ]; then
              BIN_NAME=$(basename "$cmd")
              echo "Building $BIN_NAME..."
              GOOS=linux GOARCH=mipsle GOMIPS=softfloat go build -ldflags="-s -w" -o "$ROOT_DIR/build/$BIN_NAME" "./$cmd"
            fi
          done

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: wlb-keenetic-softfloat
          path: build/*
