name: Build Softfloat MIPS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Build MIPSLE Softfloat Binaries
        run: |
          mkdir -p build
          # Поиск директории с go.mod и сборка
          GOMOD_DIR=$(dirname $(find . -maxdepth 3 -name "go.mod" | head -n 1))
          echo "Found go.mod in $GOMOD_DIR"
          cd "$GOMOD_DIR"
          
          GOOS=linux GOARCH=mipsle GOMIPS=softfloat go build -ldflags="-s -w" -o ../build/headless-vk-bot ./cmd/headless-vk-bot || true
          GOOS=linux GOARCH=mipsle GOMIPS=softfloat go build -ldflags="-s -w" -o ../build/headless-telemost-creator ./cmd/headless-telemost-creator || true
          GOOS=linux GOARCH=mipsle GOMIPS=softfloat go build -ldflags="-s -w" -o ../build/headless-telemost-joiner ./cmd/headless-telemost-joiner || true
          GOOS=linux GOARCH=mipsle GOMIPS=softfloat go build -ldflags="-s -w" -o ../build/headless-vk-creator ./cmd/headless-vk-creator || true
          GOOS=linux GOARCH=mipsle GOMIPS=softfloat go build -ldflags="-s -w" -o ../build/headless-wbstream-creator ./cmd/headless-wbstream-creator || true
          GOOS=linux GOARCH=mipsle GOMIPS=softfloat go build -ldflags="-s -w" -o ../build/headless-wbstream-joiner ./cmd/headless-wbstream-joiner || true
          GOOS=linux GOARCH=mipsle GOMIPS=softfloat go build -ldflags="-s -w" -o ../build/headless-dion-creator ./cmd/headless-dion-creator || true
          GOOS=linux GOARCH=mipsle GOMIPS=softfloat go build -ldflags="-s -w" -o ../build/headless-dion-joiner ./cmd/headless-dion-joiner || true

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: wlb-keenetic-softfloat
          path: build/*
